WITH definitions(service_code, question_key, prompt, question_type, required, display_order, condition_key, condition_value) AS (
    VALUES
        ('HOME_RENOVATION','renovation_scope','What part of the property should be renovated?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('HOME_RENOVATION','property_type','What type of property is it?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('HOME_RENOVATION','project_size','Approximately how large is the renovation area?','NUMBER',TRUE,40,NULL,NULL),
        ('HOME_RENOVATION','occupied_during_work','Will the property be occupied during the renovation?','BOOLEAN',TRUE,50,NULL,NULL),
        ('HOME_RENOVATION','budget','What approximate budget are you considering?','MONEY',FALSE,60,NULL,NULL),
        ('HOME_CLEANING','service_frequency','How often do you need cleaning?','SINGLE_CHOICE',TRUE,50,'cleaning_type','REGULAR'),
        ('PLUMBING','preferred_date','When would you like the plumbing work done?','DATE',TRUE,70,NULL,NULL),
        ('ELECTRICAL','preferred_date','When would you like the electrical work done?','DATE',TRUE,70,NULL,NULL),
        ('FLOORING','materials_purchased','Have you already purchased the flooring material?','BOOLEAN',TRUE,50,'work_type','INSTALL'),
        ('FLOORING','preferred_date','When would you like the flooring work done?','DATE',TRUE,70,NULL,NULL),
        ('APPLIANCE_REPAIR','preferred_date','When would you like the appliance repaired?','DATE',TRUE,70,NULL,NULL),
        ('PAINTING','painting_area','Is the work interior, exterior, or both?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('PAINTING','surfaces','Which rooms or surfaces should be painted?','TEXT',TRUE,30,NULL,NULL),
        ('PAINTING','project_size','Approximately how many rooms or square metres are involved?','TEXT',TRUE,40,NULL,NULL),
        ('PAINTING','preparation_needed','How much preparation is needed?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('PAINTING','paint_supplied','Will you supply the paint?','SINGLE_CHOICE',TRUE,60,NULL,NULL),

        ('CAR_REPAIR','vehicle_details','What is the vehicle make, model, and year?','TEXT',TRUE,20,NULL,NULL),
        ('CAR_REPAIR','problem_type','What problem or repair do you need help with?','TEXT',TRUE,30,NULL,NULL),
        ('CAR_REPAIR','vehicle_drivable','Is the vehicle drivable?','BOOLEAN',TRUE,40,NULL,NULL),
        ('CAR_REPAIR','urgent','Is the repair urgent?','BOOLEAN',TRUE,50,NULL,NULL),
        ('VEHICLE_DIAGNOSTICS','vehicle_details','What is the vehicle make, model, and year?','TEXT',TRUE,20,NULL,NULL),
        ('VEHICLE_DIAGNOSTICS','symptoms','Which warning lights or symptoms are present?','TEXT',TRUE,30,NULL,NULL),
        ('VEHICLE_DIAGNOSTICS','vehicle_drivable','Is the vehicle drivable?','BOOLEAN',TRUE,40,NULL,NULL),
        ('TIRE_SERVICE','tire_work_type','What tire service do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('TIRE_SERVICE','tire_size','What is the tire size, if known?','TEXT',FALSE,30,NULL,NULL),
        ('TIRE_SERVICE','tires_available','Do you already have the tires?','BOOLEAN',TRUE,40,NULL,NULL),
        ('CAR_DETAILING','detailing_scope','Which detailing service do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('CAR_DETAILING','vehicle_type','What type of vehicle is it?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('CAR_DETAILING','special_treatment','Do you need stain, odor, polish, or coating treatment?','TEXT',FALSE,40,NULL,NULL),
        ('CAR_DETAILING','mobile_service','Would you prefer a mobile service?','BOOLEAN',TRUE,50,NULL,NULL),
        ('TOWING_ROADSIDE','roadside_assistance_type','What roadside help do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('TOWING_ROADSIDE','vehicle_type','What type of vehicle is it?','TEXT',TRUE,30,NULL,NULL),
        ('TOWING_ROADSIDE','service_timing','Do you need help immediately or at a scheduled time?','SINGLE_CHOICE',TRUE,40,NULL,NULL),

        ('MOVING_HELP','property_size','How large is the property or how many rooms are involved?','TEXT',TRUE,40,NULL,NULL),
        ('MOVING_HELP','pickup_floor','Which floor is the pickup property on?','NUMBER',TRUE,45,'property_type','APARTMENT'),
        ('MOVING_HELP','destination_access','Describe the destination floor and elevator access.','TEXT',TRUE,50,NULL,NULL),
        ('MOVING_HELP','special_items','Are there heavy or special items to move?','TEXT',FALSE,55,NULL,NULL),
        ('PACKING_HELP','packing_scope','Do you need packing, unpacking, or both?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('PACKING_HELP','property_size','How large is the property or how many rooms are involved?','TEXT',TRUE,30,NULL,NULL),
        ('PACKING_HELP','materials_needed','Should the professional provide packing materials?','BOOLEAN',TRUE,40,NULL,NULL),
        ('FURNITURE_ASSEMBLY','assembly_scope','Do you need assembly, disassembly, or both?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('FURNITURE_ASSEMBLY','furniture_details','What furniture and quantity are involved?','TEXT',TRUE,30,NULL,NULL),
        ('FURNITURE_ASSEMBLY','wall_mounting','Is wall mounting required?','BOOLEAN',TRUE,40,NULL,NULL),
        ('JUNK_REMOVAL','item_types','What items should be removed?','TEXT',TRUE,20,NULL,NULL),
        ('JUNK_REMOVAL','item_volume','What is the approximate volume?','TEXT',TRUE,30,NULL,NULL),
        ('JUNK_REMOVAL','access_details','Which floor and elevator access are available?','TEXT',TRUE,40,NULL,NULL),
        ('JUNK_REMOVAL','hazardous_material','Could any item contain hazardous material?','SINGLE_CHOICE',TRUE,50,NULL,NULL),

        ('COMPUTER_SUPPORT','device_details','Which device and operating system need support?','TEXT',TRUE,20,NULL,NULL),
        ('COMPUTER_SUPPORT','problem_type','What problem are you experiencing?','TEXT',TRUE,30,NULL,NULL),
        ('COMPUTER_SUPPORT','device_usable','Is the device currently usable?','BOOLEAN',TRUE,40,NULL,NULL),
        ('NETWORK_SETUP','property_use','Is this for a home or business?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('NETWORK_SETUP','network_issue','Do you need setup, coverage, connection, or security help?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('NETWORK_SETUP','equipment_available','Do you already have the router or network equipment?','BOOLEAN',TRUE,40,NULL,NULL),
        ('NETWORK_SETUP','property_size','How large is the property and how many floors does it have?','TEXT',TRUE,50,NULL,NULL),
        ('PHONE_TABLET_REPAIR','device_details','What is the device brand and model?','TEXT',TRUE,20,NULL,NULL),
        ('PHONE_TABLET_REPAIR','repair_type','What needs repair?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('PHONE_TABLET_REPAIR','device_powers_on','Does the device power on?','BOOLEAN',TRUE,40,NULL,NULL),
        ('WEBSITE_DEVELOPMENT','website_work','Do you need a new website or improvements to an existing one?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('WEBSITE_DEVELOPMENT','website_type','What type of website is it?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('WEBSITE_DEVELOPMENT','features','Which pages and features are required?','TEXT',TRUE,40,NULL,NULL),
        ('WEBSITE_DEVELOPMENT','assets_available','Are content and design assets available?','BOOLEAN',TRUE,50,NULL,NULL),
        ('WEBSITE_DEVELOPMENT','budget','What approximate budget are you considering?','MONEY',FALSE,55,NULL,NULL),

        ('ACCOUNTING','accounting_type','What accounting help do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('ACCOUNTING','business_type','What type of business is it?','TEXT',TRUE,30,NULL,NULL),
        ('ACCOUNTING','business_volume','What is the approximate transaction or employee volume?','TEXT',TRUE,40,NULL,NULL),
        ('ACCOUNTING','service_frequency','Is this one-time or recurring work?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('ADMIN_SUPPORT','admin_task_type','What administrative tasks need support?','TEXT',TRUE,20,NULL,NULL),
        ('ADMIN_SUPPORT','work_volume','How many hours or what volume of work is expected?','TEXT',TRUE,30,NULL,NULL),
        ('ADMIN_SUPPORT','service_frequency','Is this one-time or recurring work?','SINGLE_CHOICE',TRUE,40,NULL,NULL),
        ('ADMIN_SUPPORT','tools_languages','Are specific tools or languages required?','TEXT',FALSE,50,NULL,NULL),
        ('BUSINESS_CONSULTING','consulting_area','Which consulting area do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('BUSINESS_CONSULTING','business_stage','What is the business stage and size?','TEXT',TRUE,30,NULL,NULL),
        ('BUSINESS_CONSULTING','desired_outcome','What outcome do you want to achieve?','TEXT',TRUE,40,NULL,NULL),
        ('BUSINESS_CONSULTING','engagement_type','Do you need one-time or ongoing support?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('DIGITAL_MARKETING','marketing_type','Which marketing services do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('DIGITAL_MARKETING','business_industry','What is your business and industry?','TEXT',TRUE,30,NULL,NULL),
        ('DIGITAL_MARKETING','existing_channels','Which marketing channels do you currently use?','TEXT',FALSE,40,NULL,NULL),
        ('DIGITAL_MARKETING','marketing_goal','What is your primary goal?','TEXT',TRUE,50,NULL,NULL),
        ('DIGITAL_MARKETING','monthly_budget','What approximate monthly budget are you considering?','MONEY',FALSE,55,NULL,NULL),

        ('EVENT_PLANNING','event_type','What type of event are you planning?','TEXT',TRUE,20,NULL,NULL),
        ('EVENT_PLANNING','event_date','When is the event?','DATE',TRUE,30,NULL,NULL),
        ('EVENT_PLANNING','guest_count','Approximately how many guests will attend?','NUMBER',TRUE,40,NULL,NULL),
        ('EVENT_PLANNING','planning_scope','Do you need full planning or selected tasks?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('EVENT_PLANNING','budget','What approximate budget are you considering?','MONEY',FALSE,55,NULL,NULL),
        ('EVENT_CATERING','event_details','What type of event is it and when will it happen?','TEXT',TRUE,20,NULL,NULL),
        ('EVENT_CATERING','guest_count','Approximately how many guests need catering?','NUMBER',TRUE,30,NULL,NULL),
        ('EVENT_CATERING','service_style','What meal or service style do you prefer?','TEXT',TRUE,40,NULL,NULL),
        ('EVENT_CATERING','dietary_requirements','What dietary requirements should be handled?','TEXT',FALSE,50,NULL,NULL),
        ('EVENT_CATERING','staff_equipment','Are serving staff or equipment needed?','TEXT',FALSE,55,NULL,NULL),
        ('EVENT_PHOTOGRAPHY','event_details','What type of event is it and when will it happen?','TEXT',TRUE,20,NULL,NULL),
        ('EVENT_PHOTOGRAPHY','coverage_hours','How many hours of coverage do you need?','NUMBER',TRUE,30,NULL,NULL),
        ('EVENT_PHOTOGRAPHY','media_type','Do you need photography, video, or both?','SINGLE_CHOICE',TRUE,40,NULL,NULL),
        ('EVENT_PHOTOGRAPHY','delivery_expectations','Describe the editing and delivery expectations.','TEXT',TRUE,50,NULL,NULL),
        ('DJ_LIVE_MUSIC','entertainment_type','What type of music provider do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('DJ_LIVE_MUSIC','event_details','What type of event is it and when will it happen?','TEXT',TRUE,30,NULL,NULL),
        ('DJ_LIVE_MUSIC','guest_count','Approximately how many guests will attend?','NUMBER',TRUE,40,NULL,NULL),
        ('DJ_LIVE_MUSIC','music_preferences','What music styles do you prefer?','TEXT',TRUE,50,NULL,NULL),
        ('DJ_LIVE_MUSIC','equipment_needed','Should the professional provide sound equipment?','BOOLEAN',TRUE,55,NULL,NULL),

        ('TUTORING','subject','Which subject needs tutoring?','TEXT',TRUE,20,NULL,NULL),
        ('TUTORING','student_level','What is the student level or age group?','TEXT',TRUE,30,NULL,NULL),
        ('TUTORING','learning_goal','What is the current challenge and desired goal?','TEXT',TRUE,40,NULL,NULL),
        ('TUTORING','class_format','Do you prefer individual or group tutoring?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('TUTORING','service_frequency','How often should lessons happen?','TEXT',TRUE,55,NULL,NULL),
        ('LANGUAGE_LESSONS','language','Which language do you want to learn?','TEXT',TRUE,20,NULL,NULL),
        ('LANGUAGE_LESSONS','current_level','What is your current level?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('LANGUAGE_LESSONS','learning_goal','What is your main language-learning goal?','SINGLE_CHOICE',TRUE,40,NULL,NULL),
        ('LANGUAGE_LESSONS','class_format','Do you prefer individual or group lessons?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('LANGUAGE_LESSONS','service_frequency','How often should lessons happen?','TEXT',TRUE,55,NULL,NULL),
        ('MUSIC_LESSONS','instrument','Which instrument or type of singing?','TEXT',TRUE,20,NULL,NULL),
        ('MUSIC_LESSONS','student_level','What is the current level and age group?','TEXT',TRUE,30,NULL,NULL),
        ('MUSIC_LESSONS','instrument_available','Is an instrument available for practice?','BOOLEAN',TRUE,40,NULL,NULL),
        ('MUSIC_LESSONS','class_format','Do you prefer individual or group lessons?','SINGLE_CHOICE',TRUE,50,NULL,NULL),
        ('MUSIC_LESSONS','service_frequency','How often should lessons happen?','TEXT',TRUE,55,NULL,NULL),
        ('CAREER_COACHING','coaching_type','What career support do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('CAREER_COACHING','career_stage','What is your current career stage?','TEXT',TRUE,30,NULL,NULL),
        ('CAREER_COACHING','desired_outcome','What outcome do you want to achieve?','TEXT',TRUE,40,NULL,NULL),
        ('CAREER_COACHING','engagement_type','Do you prefer one session or a package?','SINGLE_CHOICE',TRUE,50,NULL,NULL),

        ('LANDSCAPING','landscaping_scope','What landscaping work do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('LANDSCAPING','garden_size','Approximately how large is the garden?','NUMBER',TRUE,30,NULL,NULL),
        ('LANDSCAPING','design_available','Do you already have a design?','BOOLEAN',TRUE,40,NULL,NULL),
        ('LANDSCAPING','budget','What approximate budget are you considering?','MONEY',FALSE,50,NULL,NULL),
        ('TREE_CARE','tree_work_type','What tree work do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('TREE_CARE','tree_details','How many trees and approximately what size?','TEXT',TRUE,30,NULL,NULL),
        ('TREE_CARE','near_hazard','Is a tree near a building or power line?','BOOLEAN',TRUE,40,NULL,NULL),
        ('TREE_CARE','waste_removal','Should the professional remove the waste?','BOOLEAN',TRUE,50,NULL,NULL),
        ('SNOW_REMOVAL','snow_area_type','Which area needs snow removal?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('SNOW_REMOVAL','area_size','Approximately how large is the area?','NUMBER',TRUE,30,NULL,NULL),
        ('SNOW_REMOVAL','service_frequency','Is this immediate or recurring service?','SINGLE_CHOICE',TRUE,40,NULL,NULL),
        ('SNOW_REMOVAL','salt_required','Is salting or additional equipment required?','BOOLEAN',TRUE,50,NULL,NULL),

        ('HANDYMAN_SERVICE','task_type','What type of handyman work is needed?','TEXT',TRUE,20,NULL,NULL),
        ('HANDYMAN_SERVICE','task_count','Approximately how many tasks are involved?','NUMBER',TRUE,30,NULL,NULL),
        ('HANDYMAN_SERVICE','materials_available','Are the necessary materials or parts available?','BOOLEAN',TRUE,40,NULL,NULL),
        ('HANDYMAN_SERVICE','equipment_requirement','Are special tools or a ladder required?','TEXT',FALSE,50,NULL,NULL),
        ('PET_CARE','care_type','What type of pet care do you need?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('PET_CARE','animal_details','What animals and how many need care?','TEXT',TRUE,30,NULL,NULL),
        ('PET_CARE','service_frequency','Is this one-time or recurring care?','SINGLE_CHOICE',TRUE,40,NULL,NULL),
        ('PET_CARE','special_needs','Describe any special needs or instructions.','TEXT',FALSE,50,NULL,NULL),
        ('PERSONAL_ASSISTANCE','personal_assistance_type','What type of personal assistance is needed?','SINGLE_CHOICE',TRUE,20,NULL,NULL),
        ('PERSONAL_ASSISTANCE','service_frequency','Is this one-time or recurring assistance?','SINGLE_CHOICE',TRUE,30,NULL,NULL),
        ('PERSONAL_ASSISTANCE','accessibility_requirements','Are there mobility or language requirements?','TEXT',FALSE,40,NULL,NULL),
        ('GENERAL_HELP','help_delivery_mode','Is this physical, remote, or flexible help?','SINGLE_CHOICE',TRUE,60,NULL,NULL)
)
INSERT INTO service_questions (
    service_id, question_key, prompt, question_type, required, display_order,
    condition_question_key, condition_value
)
SELECT service.id, definition.question_key, definition.prompt, definition.question_type,
       definition.required, definition.display_order, definition.condition_key, definition.condition_value
FROM definitions definition
JOIN marketplace_services service ON service.code = definition.service_code
ON CONFLICT (service_id, question_key) DO UPDATE SET
    prompt = EXCLUDED.prompt,
    question_type = EXCLUDED.question_type,
    required = EXCLUDED.required,
    display_order = EXCLUDED.display_order,
    condition_question_key = EXCLUDED.condition_question_key,
    condition_value = EXCLUDED.condition_value,
    active = TRUE,
    updated_at = NOW();

UPDATE service_questions
SET display_order = CASE
    WHEN question_key = 'task_details' THEN 10
    WHEN question_key = 'delivery_mode' THEN 60
    WHEN question_key IN ('preferred_date', 'preferred_start_date') THEN 70
    WHEN question_key IN ('project_location', 'service_location', 'moving_from') THEN 80
    WHEN question_key IN ('project_postcode', 'service_postcode', 'pickup_postcode') THEN 81
    WHEN question_key = 'moving_to' THEN 90
    WHEN question_key = 'destination_postcode' THEN 91
    ELSE display_order
END,
updated_at = NOW();
