WITH options(question_key, option_value, label, display_order) AS (
    VALUES
        ('renovation_scope','KITCHEN','Kitchen',1),('renovation_scope','BATHROOM','Bathroom',2),
        ('renovation_scope','ROOMS','One or more rooms',3),('renovation_scope','WHOLE_PROPERTY','Whole property',4),
        ('renovation_scope','OTHER','Other',5),
        ('property_type','APARTMENT','Apartment',1),('property_type','HOUSE','House',2),
        ('property_type','COMMERCIAL','Commercial property',3),('property_type','OTHER','Other',4),
        ('service_frequency','ONE_TIME','One time',1),('service_frequency','WEEKLY','Weekly',2),
        ('service_frequency','MONTHLY','Monthly',3),('service_frequency','RECURRING','Other recurring schedule',4),
        ('service_frequency','UNSURE','Not sure',5),
        ('painting_area','INTERIOR','Interior',1),('painting_area','EXTERIOR','Exterior',2),('painting_area','BOTH','Both',3),
        ('preparation_needed','UNSURE','Not sure',1),('preparation_needed','MINOR','Minor preparation',2),
        ('preparation_needed','MAJOR','Major preparation',3),
        ('paint_supplied','YES','Yes',1),('paint_supplied','NO','No',2),('paint_supplied','UNSURE','Not sure',3),
        ('tire_work_type','CHANGE','Tire change',1),('tire_work_type','REPAIR','Repair',2),
        ('tire_work_type','BALANCE','Balance',3),('tire_work_type','STORAGE','Storage',4),
        ('detailing_scope','INTERIOR','Interior',1),('detailing_scope','EXTERIOR','Exterior',2),('detailing_scope','BOTH','Both',3),
        ('vehicle_type','CAR','Car',1),('vehicle_type','VAN','Van',2),('vehicle_type','SUV','SUV',3),('vehicle_type','OTHER','Other',4),
        ('roadside_assistance_type','BREAKDOWN','Breakdown recovery',1),('roadside_assistance_type','BATTERY','Battery help',2),
        ('roadside_assistance_type','FLAT_TIRE','Flat tire',3),('roadside_assistance_type','LOCKED_OUT','Locked out',4),
        ('roadside_assistance_type','TRANSPORT','Vehicle transport',5),
        ('service_timing','IMMEDIATE','Immediately',1),('service_timing','SCHEDULED','Scheduled',2),
        ('packing_scope','PACKING','Packing',1),('packing_scope','UNPACKING','Unpacking',2),('packing_scope','BOTH','Both',3),
        ('assembly_scope','ASSEMBLE','Assembly',1),('assembly_scope','DISASSEMBLE','Disassembly',2),('assembly_scope','BOTH','Both',3),
        ('hazardous_material','NO','No',1),('hazardous_material','YES','Yes',2),('hazardous_material','UNSURE','Not sure',3),
        ('property_use','HOME','Home',1),('property_use','BUSINESS','Business',2),
        ('network_issue','SETUP','New setup',1),('network_issue','COVERAGE','Poor coverage',2),
        ('network_issue','CONNECTION','Connection failure',3),('network_issue','SECURITY','Security',4),
        ('repair_type','SCREEN','Screen',1),('repair_type','BATTERY','Battery',2),
        ('repair_type','CHARGING','Charging',3),('repair_type','WATER_DAMAGE','Water damage',4),('repair_type','OTHER','Other',5),
        ('website_work','NEW','New website',1),('website_work','IMPROVE','Improve existing website',2),
        ('website_type','BUSINESS','Business website',1),('website_type','ECOMMERCE','Online store',2),
        ('website_type','PORTFOLIO','Portfolio',3),('website_type','OTHER','Other',4),
        ('accounting_type','BOOKKEEPING','Bookkeeping',1),('accounting_type','TAX','Tax',2),
        ('accounting_type','PAYROLL','Payroll',3),('accounting_type','ANNUAL_ACCOUNTS','Annual accounts',4),('accounting_type','OTHER','Other',5),
        ('consulting_area','STRATEGY','Strategy',1),('consulting_area','OPERATIONS','Operations',2),
        ('consulting_area','STARTUP','Startup',3),('consulting_area','GROWTH','Growth',4),('consulting_area','OTHER','Other',5),
        ('engagement_type','ONE_TIME','One time',1),('engagement_type','ONGOING','Ongoing',2),
        ('marketing_type','SEO','SEO',1),('marketing_type','ADVERTISING','Advertising',2),
        ('marketing_type','SOCIAL_MEDIA','Social media',3),('marketing_type','CONTENT','Content',4),('marketing_type','MULTIPLE','Multiple services',5),
        ('planning_scope','FULL','Full planning',1),('planning_scope','SELECTED_TASKS','Selected tasks',2),
        ('media_type','PHOTO','Photography',1),('media_type','VIDEO','Video',2),('media_type','BOTH','Both',3),
        ('entertainment_type','DJ','DJ',1),('entertainment_type','BAND','Band',2),
        ('entertainment_type','SOLO','Solo musician',3),('entertainment_type','UNSURE','Not sure',4),
        ('class_format','INDIVIDUAL','Individual',1),('class_format','GROUP','Group',2),('class_format','FLEXIBLE','Flexible',3),
        ('current_level','BEGINNER','Beginner',1),('current_level','INTERMEDIATE','Intermediate',2),
        ('current_level','ADVANCED','Advanced',3),('current_level','UNSURE','Not sure',4),
        ('learning_goal','CONVERSATION','Conversation',1),('learning_goal','WORK','Work',2),
        ('learning_goal','EXAM','Exam',3),('learning_goal','GENERAL','General learning',4),
        ('coaching_type','CAREER_PLANNING','Career planning',1),('coaching_type','CV','CV or resume',2),
        ('coaching_type','INTERVIEW','Interview preparation',3),('coaching_type','JOB_SEARCH','Job search',4),('coaching_type','MULTIPLE','Multiple',5),
        ('landscaping_scope','DESIGN','Garden design',1),('landscaping_scope','PATIO_PAVING','Patio or paving',2),
        ('landscaping_scope','PLANTING','Planting',3),('landscaping_scope','FULL','Full transformation',4),
        ('tree_work_type','PRUNE','Pruning',1),('tree_work_type','ASSESS','Assessment',2),
        ('tree_work_type','REMOVE_TREE','Remove tree',3),('tree_work_type','REMOVE_STUMP','Remove stump',4),
        ('snow_area_type','DRIVEWAY','Driveway',1),('snow_area_type','PATH','Path',2),
        ('snow_area_type','ROOF','Roof',3),('snow_area_type','COMMERCIAL','Commercial area',4),
        ('care_type','DOG_WALKING','Dog walking',1),('care_type','PET_SITTING','Pet sitting',2),
        ('care_type','FEEDING_VISIT','Feeding or visit',3),('care_type','TRANSPORT','Pet transport',4),
        ('personal_assistance_type','ERRANDS','Errands',1),('personal_assistance_type','SHOPPING','Shopping',2),
        ('personal_assistance_type','ORGANIZATION','Organization',3),('personal_assistance_type','APPOINTMENT','Appointment support',4),
        ('personal_assistance_type','OTHER','Other',5),
        ('delivery_mode','REMOTE','Remote',1),('delivery_mode','ON_SITE','On site',2),('delivery_mode','FLEXIBLE','Flexible',3),
        ('help_delivery_mode','PHYSICAL','Physical',1),('help_delivery_mode','REMOTE','Remote',2),('help_delivery_mode','FLEXIBLE','Flexible',3)
)
INSERT INTO question_options (question_id, option_value, label, display_order)
SELECT question.id, option.option_value, option.label, option.display_order
FROM options option
JOIN service_questions question ON question.question_key = option.question_key
ON CONFLICT (question_id, option_value) DO UPDATE SET
    label = EXCLUDED.label,
    display_order = EXCLUDED.display_order;
